remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Canonical Quoted Text
description: an algorithm for putting text in a standard form before hashing or signing
show_downloads: true