[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "canonical-quoted-text"
version = "3.17.0"
description = "Reference implementation of Canonical Quoted Text 3.17"
requires-python = ">=3.10"
dependencies = [
    "unicodedata2==17.0.0",
]

[project.optional-dependencies]
test = [
    "pytest==8.4.1",
]

[tool.pytest.ini_options]
testpaths = ["test_cqt.py"]

[tool.setuptools]
py-modules = ["cqt"]
