name: check links in markdown files

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --exclude '(doi|genderit)\.org' *.md
          fail: true
